# Generated by Django 4.2.7 on 2023-11-19 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggingmoves',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
